import { CONFIG } from '../../config.js';
import type { SkillBootstrap } from '../types.js';
import type { GitHubClient, RepoClient } from '../../types.js';

export interface ApplyResult {
  /** PR URL if this was a GitHub-backed repo with write access, else null (wrote locally). */
  pr_url: string | null;
  files: string[];
}

/**
 * Persists a completed bootstrap: writes bisect-skills/skill.md and one file per detected
 * service under bisect-skills/references/. The bootstrap instructions themselves
 * (first-time.md) live only in bisect's own repo — see src/skills/first-time.md — and are
 * never copied into the target codebase.
 *
 * On a GitHub-backed repo with write access this goes out as a PR rather than a silent
 * commit — a new folder full of auto-generated docs is exactly the kind of change a human
 * should glance at before it lands.
 */
export async function applyBootstrap(
  repo: RepoClient,
  github: GitHubClient,
  bootstrap: SkillBootstrap,
): Promise<ApplyResult> {
  const dir = CONFIG.skills.dir;
  const files = [
    { path: `${dir}/skill.md`, content: bootstrap.skill_md },
    ...bootstrap.references.map((r) => ({
      path: `${dir}/references/${r.name}.md`,
      content: r.content,
    })),
  ];

  if (github.available()) {
    const branch = `bisect/skills-bootstrap-${Date.now()}`;
    const prUrl = await github.commitAndOpenPr({
      branch,
      title: 'bisect: add bisect-skills/ routing for bug investigation',
      body:
        `Auto-generated by bisect's first-run codebase mapping.\n\n` +
        `This folder lets future bug reports route straight to the right service ` +
        `(PostHog, AWS, etc.) instead of rediscovering the codebase each time. Review ` +
        `before merging — \`skill.md\` is read on every investigation, so keep it accurate.\n\n` +
        `Files added:\n${files.map((f) => `- \`${f.path}\``).join('\n')}`,
      files,
    });
    return { pr_url: prUrl, files: files.map((f) => f.path) };
  }

  // Local REPO_PATH dev mode — no PR machinery, just write the files directly.
  for (const f of files) await repo.write(f.path, f.content);
  return { pr_url: null, files: files.map((f) => f.path) };
}
